
function autocomplete(inp, arr) {
    /*the autocomplete function takes two arguments,
    the text field element and an array of possible autocompleted values:*/
    var currentFocus;
    /*execute a function when someone writes in the text field:*/
    inp.addEventListener("input", function(e) {
        var a, b, i, val = this.value;
        /*close any already open lists of autocompleted values*/
        closeAllLists();
        if (!val) { return false;}
        currentFocus = -1;
        /*create a DIV element that will contain the items (values):*/
        a = document.createElement("DIV");
        a.setAttribute("id", this.id + "autocomplete-list");
        a.setAttribute("class", "autocomplete-items");
        /*append the DIV element as a child of the autocomplete container:*/
        this.parentNode.appendChild(a);
        /*for each item in the array...*/
        for (i = 0; i < arr.length; i++) {
          /*check if the item starts with the same letters as the text field value:*/
          if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
            /*create a DIV element for each matching element:*/
            b = document.createElement("DIV");
            /*make the matching letters bold:*/
            b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
            b.innerHTML += arr[i].substr(val.length);
            /*insert a input field that will hold the current array item's value:*/
            b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
            /*execute a function when someone clicks on the item value (DIV element):*/
            b.addEventListener("click", function(e) {
                /*insert the value for the autocomplete text field:*/
                inp.value = this.getElementsByTagName("input")[0].value;
                /*close the list of autocompleted values,
                (or any other open lists of autocompleted values:*/
                closeAllLists();
            });
            a.appendChild(b);
          }
        }
    });
    /*execute a function presses a key on the keyboard:*/
    inp.addEventListener("keydown", function(e) {
        var x = document.getElementById(this.id + "autocomplete-list");
        if (x) x = x.getElementsByTagName("div");
        if (e.keyCode == 40) {
          /*If the arrow DOWN key is pressed,
          increase the currentFocus variable:*/
          currentFocus++;
          /*and and make the current item more visible:*/
          addActive(x);
        } else if (e.keyCode == 38) { //up
          /*If the arrow UP key is pressed,
          decrease the currentFocus variable:*/
          currentFocus--;
          /*and and make the current item more visible:*/
          addActive(x);
        } else if (e.keyCode == 13) {
          /*If the ENTER key is pressed, prevent the form from being submitted,*/
          e.preventDefault();
          if (currentFocus > -1) {
            /*and simulate a click on the "active" item:*/
            if (x) x[currentFocus].click();
          }
        }
    });
    function addActive(x) {
      /*a function to classify an item as "active":*/
      if (!x) return false;
      /*start by removing the "active" class on all items:*/
      removeActive(x);
      if (currentFocus >= x.length) currentFocus = 0;
      if (currentFocus < 0) currentFocus = (x.length - 1);
      /*add class "autocomplete-active":*/
      x[currentFocus].classList.add("autocomplete-active");
    }
    function removeActive(x) {
      /*a function to remove the "active" class from all autocomplete items:*/
      for (var i = 0; i < x.length; i++) {
        x[i].classList.remove("autocomplete-active");
      }
    }
    function closeAllLists(elmnt) {
      /*close all autocomplete lists in the document,
      except the one passed as an argument:*/
      var x = document.getElementsByClassName("autocomplete-items");
      for (var i = 0; i < x.length; i++) {
        if (elmnt != x[i] && elmnt != inp) {
          x[i].parentNode.removeChild(x[i]);
        }
      }
    }
    /*execute a function when someone clicks in the document:*/
    document.addEventListener("click", function (e) {
        closeAllLists(e.target);
    });
  }
  
  /*An array containing major locations in Cameroon*/
  var combinedLocations = [
    // Douala
    "Douala International Airport, Douala",
    "Hotel La Falaise, Douala",
    "Star Land Hotel, Douala",
    "Pullman Douala Rabingha, Douala",
    "Sawa Hotel, Douala",
    "Hotel Akwa Palace, Douala",
    "Le Meridien Douala, Douala",
    "Ibis Douala, Douala",
    "Hotel Prince de Galles, Douala",
    "Hotel Lumiere Joss, Douala",
    "Hotel Beausejour Mirabel, Douala",
    "Krystal Palace, Douala",
    "Hotel Le Paradis, Douala",
    "Marcsons Hotel, Douala",
    "Hotel Residence La Falaise, Douala",
    "Hotel Lumiere Akwa, Douala",
    "Hotel De France, Douala",
    "Hotel La Vallée, Douala",
    "Bano Palace Hotel, Douala",
    "Lewat Hotel, Douala",
    "Hotel Royal Palace, Douala",
    "Hotel Lumière Njoh, Douala",
    "Residence Le Carat, Douala",
    "Hotel Résidence La Falaise Bonanjo, Douala",
    "Hotel Particular, Douala",
    "Hotel Royal, Douala",
    "Hotel Joanes, Douala",
    "Phoenix Hotel, Douala",
    "Hotel Prince de Galles Akwa, Douala",
    "Residence Hoteliere Starland, Douala",
    "Hotel Noubou International, Douala",
    "Hotel Minotel Vallée des Princes, Douala",
    "Hotel Lumiere, Douala",
    "Hotel Felicia, Douala",
    "Hotel Safyad, Douala",
    "Hotel Le Dauphin, Douala",
    "Hotel Prince de Galles Bonapriso, Douala",
    "Hotel Residence L'Empire, Douala",
    "Hotel Serena Palace, Douala",
    "Hotel Belle Vue, Douala",
    "Hotel Prince de Galles Akwa Nord, Douala",
    "Hotel Particular Palace, Douala",
    "Hotel Royale, Douala",
    "Hotel Lumiere Bonanjo, Douala",
    "Hotel Résidence Elisee, Douala",
    "Hotel Particular Palace, Douala",
    "Hotel St James, Douala",
    "Hotel Prince de Galles Deido, Douala",
    "Hotel Le Méridien Bonanjo, Douala",
    "Hotel La Falaise Bonapriso, Douala",
    "Hotel Belle Époque, Douala",
    "Hotel Résidence Elisée Bonanjo, Douala",
    "Hotel Minotel Vallée des Princes Bonanjo, Douala",
    "Hotel Lumiere Bonapriso, Douala",
    "Hotel Résidence Akwa Palace, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso, Douala",
    "Hotel Lumiere Akwa Nord, Douala",
    "Hotel Prince de Galles Deido Bonanjo, Douala",
    "Hotel Akwa Palace Bonanjo, Douala",
    "Hotel Lumiere Bonapriso, Douala",
    "Hotel Résidence Elisée Akwa, Douala",
    "Hotel Résidence Akwa Palace Bonanjo, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo, Douala",
    "Hotel Prince de Galles Bonapriso, Douala",
    "Hotel Akwa Palace Bonanjo Bonapriso, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Akwa, Douala",
    "Hotel Résidence Elisée Bonanjo Akwa, Douala",
    "Hotel Lumiere Bonapriso Akwa, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Akwa, Douala",
    "Hotel Akwa Palace Bonanjo Bonapriso Akwa, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo, Douala",
    "Hotel Résidence Elisée Bonanjo Akwa Bonapriso, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Akwa Nord, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord, Douala",
    "Hotel Akwa Palace Bonanjo Bonapriso Akwa Nord, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido, Douala",
    "Hotel Résidence Elisée Bonanjo Akwa Bonapriso Akwa Nord Deido, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Akwa Nord Deido, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport, Douala",
    "Hotel Akwa Palace Bonanjo Bonapriso Akwa Nord Deido Douala International Airport, Douala",
    "Hotel Résidence Elisée Bonanjo Akwa Bonapriso Akwa Nord Deido Douala International Airport, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport Bonapriso, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa, Douala",
    "Hotel Akwa Palace Bonanjo Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo, Douala",
    "Hotel Résidence Elisée Bonanjo Akwa Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo, Douala",
    "Hotel Résidence Elisée Bonanjo Akwa Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa, Douala",
    "Hotel Akwa Palace Bonanjo Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso, Douala",
    "Hotel Résidence Elisée Bonanjo Akwa Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo, Douala",
    "Hotel Akwa Palace Bonanjo Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa, Douala",
    "Hotel Akwa Palace Bonanjo Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso, Douala",
    "Hotel Résidence Elisée Bonanjo Akwa Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso, Douala",
    "Hotel Résidence Elisée Bonanjo Akwa Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso, Douala",
    "Hotel Résidence Elisée Bonanjo Akwa Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport, Douala",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa, Douala",
    "Hotel Lumiere Bonapriso Akwa Bonanjo Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso, Douala",
    "Hotel Akwa Palace Bonanjo Bonapriso Akwa Nord Deido Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport Bonapriso Akwa Bonanjo Bonapriso Akwa Bonanjo Douala International Airport, Douala",
  
    // Yaounde
    "Yaounde Nsimalen International Airport, Yaounde",
    "Hilton Yaounde, Yaounde",
    "Djeuga Palace, Yaounde",
    "Hotel Franco, Yaounde",
    "Hotel des Deputes, Yaounde",
    "Merina Hotel, Yaounde",
    "Hotel Residence La Falaise, Yaounde",
    "Hotel Mont Fébé, Yaounde",
    "Hotel Mansel, Yaounde",
    "Hotel Azur, Yaounde",
    "Felydac Hotel, Yaounde",
    "Hotel Le Diplomate, Yaounde",
    "Hotel Azur, Yaounde",
    "Hotel Le Relais Saint-Hubert, Yaounde",
    "Hotel du Boulevard, Yaounde",
    "Hotel La Falaise, Yaounde",
    "Hotel Mont Fébé, Yaounde",
    "Hotel Résidence La Falaise, Yaounde",
    "Hotel Minotel Vallée des Princes, Yaounde",
    "Hotel des Parlementaires, Yaounde",
    "Hotel Residence Jouvence, Yaounde",
    "Hotel Le Triskell, Yaounde",
    "Hotel Tchatcha, Yaounde",
    "Hotel Jouvence International, Yaounde",
    "Hotel Résidence Halimo, Yaounde",
    "Hotel Merina, Yaounde",
    "Hotel Prince de Galles, Yaounde",
    "Hotel Royal Palace, Yaounde",
    "Hotel Résidence La Falaise Bonapriso, Yaounde",
    "Hotel Mont Fébé Yaounde, Yaounde",
    "Hotel Résidence Jouvence Bonapriso, Yaounde",
    "Hotel La Falaise Bonapriso, Yaounde",
    "Hotel Résidence Akwa Palace, Yaounde",
    "Hotel Résidence Elisée, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonanjo, Yaounde",
    "Hotel Résidence Akwa Palace Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo, Yaounde",
    "Hotel Mont Fébé Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Jouvence Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Lumiere Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
    "Hotel Résidence Elisée Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Résidence Jouvence Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso, Yaounde",
    "Hotel Minotel Vallée des Princes Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo, Yaounde",
    "Hotel Résidence La Falaise Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonanjo Bonapriso Bonanjo Bonanjo Bonapriso Bonapriso Bonanjo Bonapriso Bonapriso Bonapriso Bonapriso Bonanjo Bonanjo, Yaounde",
  ];
  
  
  /*initiate the autocomplete function on the "myInput" element, and pass along the airports array as possible autocomplete values:*/
  autocomplete(document.getElementById("myInput6"), combinedLocations);